pipeline {
    agent {
        node {
            label 'node1'
        }
    }
    stages {
        stage('build') {
            step {
                sh 'pip3 install -f s05/python-simple-app/requirements.txt'
            }
        }
        stage('run') {
            step {
                sh 'python3 s05/python-simple-app/app.py &'
            }
        }
        stage('test') {
            step {
                sh 'sleep 30 && curl -s localhost:8080'
            }
        }
        stage('cleanup') {
            step {
                sh 'fuser -k 8080/tcp'
            }
        }
    }
}